import { Client, Prospect } from './types';

export const sampleClients: Client[] = [
  {
    id: '1',
    name: 'Carlos Eduardo Silva',
    phone: '5511999990001',
    email: 'carlos@email.com',
    vehicle: 'Toyota Corolla 2023',
    vehicleType: 'car',
    plate: 'ABC-1D23',
    plan: 'Proteção Completa',
    monthlyValue: 159.90,
    dueDate: '2026-06-15',
    status: 'paid',
    notes: '',
  },
  {
    id: '2',
    name: 'Maria Fernanda Costa',
    phone: '5511999990002',
    email: 'maria@email.com',
    vehicle: 'Honda CG 160 Titan',
    vehicleType: 'motorcycle',
    plate: 'XYZ-9E87',
    plan: 'Proteção Moto',
    monthlyValue: 59.90,
    dueDate: '2026-06-10',
    status: 'unpaid',
    notes: 'Segundo mês em atraso',
  },
  {
    id: '3',
    name: 'João Pedro Almeida',
    phone: '5511999990003',
    email: 'joao@email.com',
    vehicle: 'Scania R450 2022',
    vehicleType: 'truck',
    plate: 'TRK-4F56',
    plan: 'Proteção Caminhão',
    monthlyValue: 289.90,
    dueDate: '2026-06-20',
    status: 'paid',
    notes: '',
  },
  {
    id: '4',
    name: 'Ana Beatriz Rodrigues',
    phone: '5511999990004',
    email: 'ana@email.com',
    vehicle: 'Hyundai HB20 2024',
    vehicleType: 'car',
    plate: 'DEF-2G34',
    plan: 'Proteção Básica',
    monthlyValue: 89.90,
    dueDate: '2026-06-05',
    status: 'unpaid',
    notes: 'Prometeu pagar dia 25',
  },
  {
    id: '5',
    name: 'Roberto Mendes Jr.',
    phone: '5511999990005',
    email: 'roberto@email.com',
    vehicle: 'Frota 8x Fiat Strada',
    vehicleType: 'fleet',
    plate: 'FROTA-05',
    plan: 'Proteção Frota',
    monthlyValue: 1599.20,
    dueDate: '2026-06-18',
    status: 'paid',
    notes: '8 veículos — R$199,90 cada',
  },
  {
    id: '6',
    name: 'Luciana Martins',
    phone: '5511999990006',
    email: 'luciana@email.com',
    vehicle: 'Fiat Ducato 2021',
    vehicleType: 'van',
    plate: 'VAN-3H78',
    plan: 'Proteção Van/Utilitário',
    monthlyValue: 189.90,
    dueDate: '2026-06-12',
    status: 'unpaid',
    notes: '',
  },
  {
    id: '7',
    name: 'Thiago Oliveira',
    phone: '5511999990007',
    email: 'thiago@email.com',
    vehicle: 'Yamaha MT-07 2024',
    vehicleType: 'motorcycle',
    plate: 'MOT-5J12',
    plan: 'Proteção Moto Premium',
    monthlyValue: 99.90,
    dueDate: '2026-06-22',
    status: 'paid',
    notes: '',
  },
];

export const sampleProspects: Prospect[] = [
  {
    id: '1',
    name: 'Fernando Souza',
    phone: '5511999880001',
    vehicle: 'Chevrolet Onix 2025',
    interest: 'Proteção contra roubo',
    notes: 'Indicação do Carlos',
    contacted: false,
  },
  {
    id: '2',
    name: 'Patrícia Lima',
    phone: '5511999880002',
    vehicle: 'Honda CB 500F',
    interest: 'Seguro completo para moto',
    notes: 'Viu no Instagram',
    contacted: true,
  },
  {
    id: '3',
    name: 'Marcos Transportes LTDA',
    phone: '5511999880003',
    vehicle: 'Frota 12 caminhões',
    interest: 'Seguro de frota com rastreamento',
    notes: 'Empresa de logística — alto potencial',
    contacted: false,
  },
];
