import { Property, Client } from './types';

export const sampleProperties: Property[] = [
  {
    id: '1',
    title: 'Apartamento Alto Padrão no Centro',
    type: 'apartment',
    transaction: 'sale',
    price: 580000,
    location: 'Rua das Flores, 450',
    neighborhood: 'Centro',
    city: 'São Paulo',
    area: 120,
    bedrooms: 3,
    bathrooms: 2,
    parkingSpots: 2,
    description: 'Apartamento luxuoso com acabamento premium, vista panorâmica e localização privilegiada.',
    features: ['Varanda Gourmet', 'Piscina', 'Academia', 'Portaria 24h'],
    images: [],
    featured: true,
  },
  {
    id: '2',
    title: 'Casa com Jardim no Jardim Europa',
    type: 'house',
    transaction: 'sale',
    price: 1200000,
    location: 'Av. dos Ipês, 1200',
    neighborhood: 'Jardim Europa',
    city: 'São Paulo',
    area: 280,
    bedrooms: 4,
    bathrooms: 3,
    parkingSpots: 3,
    description: 'Casa espaçosa com jardim amplo, churrasqueira e piscina. Ideal para famílias.',
    features: ['Churrasqueira', 'Piscina', 'Jardim', 'Suíte Master'],
    images: [],
    featured: true,
  },
  {
    id: '3',
    title: 'Studio Moderno em Pinheiros',
    type: 'apartment',
    transaction: 'rent',
    price: 2800,
    location: 'Rua Teodoro Sampaio, 800',
    neighborhood: 'Pinheiros',
    city: 'São Paulo',
    area: 45,
    bedrooms: 1,
    bathrooms: 1,
    parkingSpots: 1,
    description: 'Studio compacto e funcional, perfeito para jovens profissionais. Próximo ao metrô.',
    features: ['Mobiliado', 'Próximo ao Metrô', 'Lavanderia', 'Coworking'],
    images: [],
    featured: false,
  },
  {
    id: '4',
    title: 'Cobertura Duplex na Vila Madalena',
    type: 'apartment',
    transaction: 'sale',
    price: 1850000,
    location: 'Rua Aspicuelta, 300',
    neighborhood: 'Vila Madalena',
    city: 'São Paulo',
    area: 200,
    bedrooms: 3,
    bathrooms: 4,
    parkingSpots: 2,
    description: 'Cobertura duplex com terraço panorâmico, acabamento de luxo e localização nobre.',
    features: ['Terraço', 'Churrasqueira', 'Spa', 'Home Theater'],
    images: [],
    featured: true,
  },
  {
    id: '5',
    title: 'Sala Comercial no Itaim Bibi',
    type: 'commercial',
    transaction: 'rent',
    price: 5500,
    location: 'Av. Brigadeiro Faria Lima, 2000',
    neighborhood: 'Itaim Bibi',
    city: 'São Paulo',
    area: 85,
    bedrooms: 0,
    bathrooms: 2,
    parkingSpots: 2,
    description: 'Sala comercial em edifício corporativo de alto padrão. Infraestrutura completa.',
    features: ['Ar Condicionado Central', 'Recepção', 'Segurança 24h', 'Estacionamento'],
    images: [],
    featured: false,
  },
  {
    id: '6',
    title: 'Casa de Condomínio em Alphaville',
    type: 'house',
    transaction: 'sale',
    price: 2100000,
    location: 'Alameda dos Guarás, 150',
    neighborhood: 'Alphaville',
    city: 'Barueri',
    area: 350,
    bedrooms: 5,
    bathrooms: 4,
    parkingSpots: 4,
    description: 'Casa em condomínio fechado com total segurança e lazer completo.',
    features: ['Condomínio Fechado', 'Piscina Aquecida', 'Quadra de Tênis', 'Sauna'],
    images: [],
    featured: true,
  },
];

export const sampleClients: Client[] = [
  {
    id: '1',
    name: 'Carlos Eduardo Silva',
    phone: '5511999990001',
    email: 'carlos@email.com',
    property: 'Apt. 302 - Ed. Monte Verde',
    contractValue: 2500,
    dueDate: '2026-06-15',
    status: 'paid',
    notes: '',
  },
  {
    id: '2',
    name: 'Maria Fernanda Costa',
    phone: '5511999990002',
    email: 'maria@email.com',
    property: 'Casa 12 - Cond. Solar',
    contractValue: 4200,
    dueDate: '2026-06-10',
    status: 'unpaid',
    notes: 'Segundo mês em atraso',
  },
  {
    id: '3',
    name: 'João Pedro Almeida',
    phone: '5511999990003',
    email: 'joao@email.com',
    property: 'Sala 1401 - Torre Business',
    contractValue: 5500,
    dueDate: '2026-06-20',
    status: 'paid',
    notes: '',
  },
  {
    id: '4',
    name: 'Ana Beatriz Rodrigues',
    phone: '5511999990004',
    email: 'ana@email.com',
    property: 'Apt. 801 - Ed. Mirante',
    contractValue: 3200,
    dueDate: '2026-06-05',
    status: 'unpaid',
    notes: 'Prometeu pagar dia 25',
  },
  {
    id: '5',
    name: 'Roberto Mendes Jr.',
    phone: '5511999990005',
    email: 'roberto@email.com',
    property: 'Lote 45 - Jardim das Acácias',
    contractValue: 1800,
    dueDate: '2026-06-18',
    status: 'paid',
    notes: '',
  },
];
